name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Connexion à GitHub Docker Registry
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Étape 3 : Construire l'image Docker
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/docker-app:latest

    # Étape 4 : Pousser l'image vers GitHub Packages
    - name: Push Docker Image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository }}/docker-app:latest
