name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Connexion à GitHub Packages
    - name: Log in to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Étape 3 : Construire l'image Docker
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/docker-app:latest

    # Étape 4 : Scanner les vulnérabilités avec Trivy
    - name: Scan Docker Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ github.repository }}/docker-app:latest
        format: table # Format de sortie pour un affichage lisible
        exit-code: 0  # Empêche l'échec si des vulnérabilités sont détectées (changer à 1 si nécessaire)
        severity: HIGH,CRITICAL  # Seules les vulnérabilités critiques ou hautes sont affichées

    # Étape 5 : Pousser l'image vers GitHub Packages
    - name: Push Docker Image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository }}/docker-app:latest
